### PR TITLE
Replace cg-comp with tree-sitter

### PR DESCRIPTION
**Pull request by sushain97**

### CODE REVIEW

**Comment by mr-martian** [comment]
LGTM

**Comment by sushain97** [comment]
Hm, this slightly undercounts rules for `apertium-tat`:

```
st-sushain2:apertium-stats-service sushain$ curl -X POST https://apertium.org/stats-service/tat/rlx?async=false | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   379  100   379    0     0     70      0  0:00:05  0:00:05 --:--:--    98
{
  "in_progress": [],
  "name": "apertium-tat",
  "stats": [
    {
      "created": "2021-03-15T05:02:20.843248869",
      "file_kind": "Rlx",
      "last_author": "mansayk",
      "last_changed": "2019-02-18T10:22:33",
      "name": "apertium-tat",
      "path": "apertium-tat.tat.rlx",
      "requested": "2021-03-15T05:02:20.047203011",
      "revision": 2134,
      "sha": "604aa339206cf675db4d61ea1ad42b09b41bd613",
      "size": 34422,
      "stat_kind": "Rules",
      "value": 123
    }
  ]
}
```

```
st-sushain2:apertium-stats-service sushain$ curl http://localhost:8000/tat/rlx?async=false | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   379  100   379    0     0    127      0  0:00:02  0:00:02 --:--:--   126
{
  "in_progress": [],
  "name": "apertium-tat",
  "stats": [
    {
      "created": "2021-03-15T05:02:46.105204600",
      "file_kind": "Rlx",
      "last_author": "mansayk",
      "last_changed": "2019-02-18T10:22:33",
      "name": "apertium-tat",
      "path": "apertium-tat.tat.rlx",
      "requested": "2021-03-15T05:02:45.718834500",
      "revision": 2134,
      "sha": "604aa339206cf675db4d61ea1ad42b09b41bd613",
      "size": 34422,
      "stat_kind": "Rules",
      "value": 121
    }
  ]
}
```

@mr-martian Any thoughts?

**Comment by mr-martian** [comment]
There was a typo in the cg grammar file that resulted in `SUBSTITUTE` rules not being parsed correctly. I'll push a fix in a little bit.

**Comment by mr-martian** [comment]
Commit 39eff02 in tree-sitter-apertium fixes this for me

**Comment by sushain97** [comment]
Yep, WFM:
```
st-sushain2:apertium-stats-service sushain$ curl http://localhost:8000/tat/rlx?async=false | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   379  100   379    0     0    124      0  0:00:03  0:00:03 --:--:--   124
{
  "in_progress": [],
  "name": "apertium-tat",
  "stats": [
    {
      "created": "2021-03-16T05:06:59.794481400",
      "file_kind": "Rlx",
      "last_author": "mansayk",
      "last_changed": "2019-02-18T10:22:33",
      "name": "apertium-tat",
      "path": "apertium-tat.tat.rlx",
      "requested": "2021-03-16T05:06:59.475736500",
      "revision": 2134,
      "sha": "604aa339206cf675db4d61ea1ad42b09b41bd613",
      "size": 34422,
      "stat_kind": "Rules",
      "value": 123
    }
  ]
}
```

**Pull request merged**
